name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      name: Checkout 
      uses: actions/checkout@v2
      name: Install NPM packages
      run: |
        npm install --save-dev
      name: Run test script
      run: |
        npm run test
