name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Setup backend test
        env:
          MONGO_URL: mongodb+srv://clippy:PyMKjByTN_g9dMS@cluster0.ovbn3.mongodb.net/Checkout?retryWrites=false&w=majority
        run: |
          cd server
          npm install jest
          npm install --save-dev
          npm run test
